sudo: required
services:
  - docker

before_install:
  - docker build -t wbruntra/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run wbruntra/react-test npm test -- --coverage

after_success:
  - docker build -t wbruntra/multi-client ./client
  - docker build -t wbruntra/multi-nginx ./nginx
  - docker build -t wbruntra/multi-server ./server 
  - docker build -t wbruntra/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push wbruntra/multi-client
  - docker push wbruntra/multi-nginx
  - docker push wbruntra/multi-server
  - docker push wbruntra/multi-worker